# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sort.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsort.proto\"\x1e\n\x0bSortRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\x0c\"\x1f\n\x0cSortResponse\x12\x0f\n\x07numbers\x18\x01 \x01(\x0c\x32\x32\n\x0bSortService\x12#\n\x04Sort\x12\x0c.SortRequest\x1a\r.SortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sort_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SORTREQUEST']._serialized_start=14
  _globals['_SORTREQUEST']._serialized_end=44
  _globals['_SORTRESPONSE']._serialized_start=46
  _globals['_SORTRESPONSE']._serialized_end=77
  _globals['_SORTSERVICE']._serialized_start=79
  _globals['_SORTSERVICE']._serialized_end=129
# @@protoc_insertion_point(module_scope)
