# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x64\x64ition.proto\"\'\n\x0f\x41\x64\x64itionRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\x10\x41\x64\x64itionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x37\n\x08\x41\x64\x64ition\x12+\n\x04\x41\x64\x64n\x12\x10.AdditionRequest\x1a\x11.AdditionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ADDITIONREQUEST']._serialized_start=18
  _globals['_ADDITIONREQUEST']._serialized_end=57
  _globals['_ADDITIONRESPONSE']._serialized_start=59
  _globals['_ADDITIONRESPONSE']._serialized_end=93
  _globals['_ADDITION']._serialized_start=95
  _globals['_ADDITION']._serialized_end=150
# @@protoc_insertion_point(module_scope)
