# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import addition_pb2 as addition__pb2


class AdditionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Addn = channel.unary_unary(
                '/Addition/Addn',
                request_serializer=addition__pb2.AdditionRequest.SerializeToString,
                response_deserializer=addition__pb2.AdditionResponse.FromString,
                )


class AdditionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Addn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdditionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Addn': grpc.unary_unary_rpc_method_handler(
                    servicer.Addn,
                    request_deserializer=addition__pb2.AdditionRequest.FromString,
                    response_serializer=addition__pb2.AdditionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Addition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Addition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Addn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Addition/Addn',
            addition__pb2.AdditionRequest.SerializeToString,
            addition__pb2.AdditionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
